---
name: Update resume.carlosnunez.me
on:
  push:
    branches:
      - main
    paths:
      - 'resumes/**'
      - 'config.toml'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'env.gpg'
      - 'scripts/deploy'
      - '.kickCI/**'

jobs:
  update_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: 2.21.0

      - name: Decrypt environment file
        run: |-
          docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Deploy!
        run: ./scripts/deploy
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}
